### ISSUE TITLE
[feature request] Automatically bundle correct version of @babel/runtime helpers

### ISSUE THREAD

**Issue by Andarist** [preconstruct/preconstruct#223]
When I have this package (`@babel/runtime`) in dependencies I'd like to have imports reference their ESM versions for ESM bundles.

I recall something like this being here in preconstruct in its early days but it seems like it's gone. Would it be possible to re-add some kind of support for this?

**Comment by mitchellhamilton** [comment]
Yeah, I removed this recently because I removed `@babel/plugin-transform-runtime` from Preconstruct in favor of consumers adding it to their Babel config(My reasoning behind that is that Preconstruct should use the same Babel config as if any other tool did a Babel transform without passing any config) I suppose we could add the cjs @babel/runtime import -> esm @babel/runtime import back though.
