### ISSUE TITLE
Support conditional exports

### ISSUE THREAD

**Issue by Andarist** [preconstruct/preconstruct#251]
It seems that [conditional exports](https://nodejs.org/api/esm.html#esm_conditional_exports) have reached consensus and are currently unflagged in node@13.

Most likely this is going to be a standard that is going to be soon-ish supported by bundlers and will take precedence over currently available "main fields". It would be good to explore adding support for it sooner than later - I intend to work on this one, as I want to understand how this algorithm really works, but I also don't have that much time lately and I have a long TODO list so if anyone cares about this as well I won't mind if anyone beats me to it.

**Comment by mitchellhamilton** [comment]
I'm definitely interested in supporting conditional exports. I assume by supporting conditional exports, you implicitly mean supporting Node ESM? The one big problem I see though is that while Node ESM and conditional exports are mostly done, Loader Hooks and what this means for bundlers/TypeScript/anything that resolves modules aren't figured out yet. The latter is especially a big deal because of how different the Node ESM module resolution algorithm is. (e.g. the biggest thing being no adding extensions, reading index files and etc.)

I think the best way to proceed might be if you want to write up what conditional export support in Preconstruct would look like, we discuss it, then you implement it and only enable when `preconstruct.experimental.nodeESM` is set to true in the project config. I'm personally in no rush for this because of the things that aren't yet figured out though.

**Comment by Andarist** [comment]
> It seems like it's a catch-22 situation where any approach breaks something else

Yep, it's basically the reason why this has not been implemented yet in Preconstruct. There is just no way (to the best of our knowledge) to make it "just work" for all the cases.

The only way I see we could move forward with this is to introduce some kinds of modes + validation rules. The easiest mode to introduce would be "esm-only" but it has a butterfly effect on both dependants (not every one can go all in with esm just yet) and dependencies (we'd have to validate every dep, including transitive ones, that the loading them would actually work). 

This stuff is way more complex beyond what it should be 😭
