### ISSUE TITLE
Consider minifying the production code and keeping track of the bundle size

### ISSUE THREAD

**Issue by lucat1** [preconstruct/preconstruct#280]
Other tools such as [microbundle](https://github.com/developit/microbundle) or [tsdx](https://github.com/jaredpalmer/tsdx) do this. As far as I've seen minifying the production code is kinda mandatory to support people using the library from tools like `unpkg` or with `snowpack`(I'm not aware it does code minification on dependencies). With that said another useful feature could be keeping track of the bundle size of the aforementioned minified build. The size tracking doesn't have to be included in this project IMHO as there are many other tools to keep track of that, but even these tools cannot work without a minified build output 😢. I can work on both of these features and open a PR if you'd like to go forward with this.

**Comment by mitchellhamilton** [comment]
We allow you to build a UMD which is minified with the `umd:main` field. Minifying the other bundles would make it much harder to debug(this wouldn't really be solved with source maps because most tools don't consume source maps from packages and they're quite slow to generate both for building packages and consumer bundlers consuming source maps and generating the end source maps from those) and given consumer bundlers will already minify code, I don't think it would really bring any benefits.

Preconstruct is intentionally quite minimal and given that you can already do size tracking with tools like https://github.com/ai/size-limit which bundle your code, I don't think this is something we want to add to Preconstruct.
