### ISSUE TITLE
Allow .mjs file extension in module field

### ISSUE THREAD

**Issue by wereHamster** [preconstruct/preconstruct#284]
Use case:

```
{
  "main": "dist/package.cjs.js",
  "exports": {
    ".": {
      "import": "./dist/package.esm.mjs",
      "default": "./dist/package.cjs.js"
    }
  },
  "module": "dist/package.esm.mjs"
}
```

**Comment by Andarist** [comment]
The goal of preconstruct is to have strict opinions about how package.json metadata related to consuming a package by different tools is written. Ultimately there is no much need for a user to control this - the tool (such as preconstruct) can enforce conventions. 

This issue here really boils down to adding support for node's conditional exports and from preconstruct's POV is not different from https://github.com/preconstruct/preconstruct/issues/251

**Comment by mitchellhamilton** [comment]
Closing since this is gonna be tracked in #251
