### ISSUE TITLE
Preconstruct creating duplicate helpers per file import

### ISSUE THREAD

**Issue by ifiokjr** [preconstruct/preconstruct#297]
## Description

[**Original Issue**](https://github.com/remirror/remirror/issues/358)

The bundle is being bloated by repeated helper functions. An example can be found [here](https://unpkg.com/browse/@remirror/core@1.0.0-next.4/dist/core.esm.js).

The following functions are duplicated multiple times for each file import. 

- `_createForOfIteratorHelper`
- `_unsupportedIterableToArray`
- `_arrayLikeToArray`
- `_objectSpread` 

I'm using this syntax which seems to cause it.

```ts
for (const str of ['a', 'b']) {
  // do stuff
}
```

## Possible Fix

I need to first understand what's causing the build issue. Is it a `babel` configuration issue, a problem with the plugins, an issue with `preconstruct` or perhaps even `rollup`?

To test run the following:

```bash
# Optional - install latest version of `pnpm`
npm i -g pnpm

git clone https://github.com/remirror/remirror
cd remirror
pnpm install
pnpm build
```

Navigate to `packages/@remirror/core/dist/core.esm.js` and observe the duplication in the files.

The `babel.config.js` is added to the root directory after running `pnpm i`.

**Comment by Andarist** [comment]
The issue is twofold:
1. My educated guess is that the issue that they are included instead of being imported is caused by not using `version` option with `@babel/plugin-transform-runtime`: https://babeljs.io/docs/en/babel-plugin-transform-runtime#version
2. they are duplicated with their consuming files because there is no special logic for helpers like there is in `@rollup/plugin-babel`: https://github.com/rollup/plugins/blob/6cd15b94cb88943d8e9bc62b7c5d71ac1fb8a457/packages/babel/src/bundledHelpersPlugin.js

**Comment by ifiokjr** [comment]
Brilliant! Just tried it and it fixed the issue.

**Comment by Andarist** [comment]
I've created issues about both things:
1. https://github.com/preconstruct/preconstruct/issues/318
2. https://github.com/preconstruct/preconstruct/issues/319
