### ISSUE TITLE
Rollup config? Unable to import images

### ISSUE THREAD

**Issue by sarahbethfederman** [preconstruct/preconstruct#304]
I have a package that imports assets that I need to build which doesn't seem to be supported? The error says I need a plugin.

Is there a way to add rollup config? I installed @rollup/plugin image and created a `rollup.config.js` in the root but it doesn't seem to be picked up. The config I'm using is 
```
import image from '@rollup/plugin-image';

export default {
  plugins: [image()],
};
```

**Comment by mitchellhamilton** [comment]
> I have a package that imports assets that I need to build which doesn't seem to be supported?

Yes, it's not supported because the behavior for importing an image and etc. is quite undefined, especially when talking about publishing packages. Should it be a path to the image? Inlined content like what @rollup/plugin-image does? Something different?

> Is there a way to add rollup config?

There is not - Rollup is intended to be an implementation detail so that things like preconstruct dev can work just like build.

---

If what you're looking for is what @rollup/plugin-image does with inlining an image, you could use babel-plugin-macros and write a macro something like https://github.com/pveyes/raw.macro (or use raw.macro if it's an svg or something like that)

**Comment by sarahbethfederman** [comment]
I took a closer look and it looks like the offending package is actually just copying the files into the dist package via `cpx 'src/common/assets/*.*' 'dist/cjs/common/assets` 

Is this something I can still run? Is there a proper way? Can I have preconstruct ignore these files in the package so that it doesn't get the unexpected character error?

**Comment by mitchellhamilton** [comment]
Running that should be fine. Preconstruct shouldn't care about them unless you're importing them in an entrypoint that Preconstruct is building. If you're importing them, you could switch the import to a require because Preconstruct won't look at require calls.

**Comment by sarahbethfederman** [comment]
This works, but hopefully there's room to consider some customization of the build in the future 👍
