### ISSUE TITLE
Discussion around babel, eslint, and typescript

### ISSUE THREAD

**Issue by sarahbethfederman** [preconstruct/preconstruct#311]
Hey, I'm just wondering if supporting the typescript compiler could possibly be an option in the future. All was working fine with the babel option and a separate typechecking command until I tried to upgrade our repo from old deprecated tslint to eslint.

I'm having a _fun_ time trying to get babel and eslint to play nice with typescript due to the fact that if you want to use eslint with babel you have to use babel's [eslint parser](https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser), which has pretty shoddy TS support atm. If you want to use typescript rules with eslint you have to use [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md) which has its own parser, making them incompatible.

It looks like babel is not really prioritizing support typescript with its eslint parser, and I'm not using a lot of babel rules, so it would be nice to have the typescript compiler as an option if that's a possibility.

**Comment by mitchellhamilton** [comment]
You can still use typescript-eslint, you don't have to use babel-eslint?

(I personally use typescript-eslint in repos that I use TypeScript + Preconstruct + ESLint in)

---

Re using the typescript compiler for compilation: The answer is probably a no. The only reason that we'd want to use the TypeScript compiler for compiling ts -> js would be to support const enums and namespaces which I don't really think would be worth it given:

- namespaces aren't generally used much these days
- const enums don't make a huge amount of sense for libraries given you're probably going to export the enums so they can't really be const enums since otherwise JS consumers couldn't use them
- It means consumers of Preconstruct have to decide whether to use tsc or Babel which is annoying
- Do we run also run Babel after the TypeScript compiler? If yes, builds would be non-trivially slower. if no, then you can't run arbitrary code transforms.
- preconstruct dev's require hook would have to use the TypeScript compiler too which would be v slow given it would have to parse every file in the TS project to compile anything rather than Babel's approach of compiling a single file. (we could use TS's transpileModule but then that makes the benefits of using the TS compiler moot)

(This is separate to "Should Preconstruct print type errors from TypeScript given it already uses the TypeScript compiler to generate declaration files?" to which the answer is "probably yes.")

**Comment by sarahbethfederman** [comment]
Didn't realize you can still use typescript-eslint! That's a bit confusing, hope the babel folks end up documenting it somewhere. I'm a noob. All g 👍
