### ISSUE TITLE
Option to replace `terser` with `esbuild`

### ISSUE THREAD

**Issue by ifiokjr** [preconstruct/preconstruct#364]
### Description

`preconstruct` is already much faster for building monorepos than most other tools. I wonder if there could be a top-level configuration to use [`esbuild`](https://esbuild.github.io/api/#minify) for minification rather than `terser` for speed gains.

I'm happy to create an exploratory PR with [`rollup-plugin-esbuild`](https://github.com/egoist/rollup-plugin-esbuild).

**Comment by mitchellhamilton** [comment]
I'm not sure it would really be worth it since terser is only used for UMD builds which are generally quite rare(and especially rare for larger projects where build time would be a big concern), terser is run in worker processes so it doesn't block other packages from being built and terser generates smaller code than esbuild(even though the size difference seems reasonably marginal).

**Comment by ifiokjr** [comment]
Makes sense, I'm happy to close this.
