### ISSUE TITLE
Module loading from its own package causes error

### ISSUE THREAD

**Issue by with-heart** [preconstruct/preconstruct#396]
If a module in a package refers to itself by its package name when importing, `preconstruct build` fails with the error `the package is not specified in dependencies or peerDependencies`. @Andarist felt that this should be reported.

See this PR review thread for more context (and @Andarist's comments): https://github.com/chakra-ui/chakra-ui/pull/3956#pullrequestreview-651624003

Example of the error:

`🎁 error @chakra-ui/utils "@chakra-ui/utils" is imported by "src/walk-object.ts" but the package is not specified in dependencies or peerDependencies`

**Comment by mitchellhamilton** [comment]
Re @Andarist's comments:

> Could you report this as a bug to preconstruct? I think this works now in node by default, according to the resolution algorithm: https://nodejs.org/api/modules.html#modules_all_together , It looks like LOAD_PACKAGE_SELF is allowing that explicitly.
> 
> I recall having some problems with that in the past and the previous version of the algorithm did not have this explicit step. However, I can't see why LOAD_NODE_MODULES would not allow this in the old algorithm so maybe this has always worked?

From testing, it seems like the LOAD_PACKAGE_SELF thing only happens when you have an `exports` field. The reason that it sort of works is that when using Yarn workspaces currently is that it's essentially just "normal" resolution of a package in your node_modules since the package is symlinked into the root node_modules directory. That also means that without an exports field, if someone isn't using Yarn workspaces(or npm's workspaces, I suspect it would fine there too), like they only have a single package or they're using pnpm, the resolution wouldn't work in Node.

So I'm kinda leaning towards keeping it as is and not allowing it for now since it would kinda be deviating from Node module resolution to have it work always (which would mean that it wouldn't work with the require hook unless we did extra hackery).

Also, there is the question of "do you emit the import to the package name or have it resolve to the actual source?"
