### ISSUE TITLE
Importing images cause error

### ISSUE THREAD

**Issue by duanra-a16a** [preconstruct/preconstruct#400]
When running `preconstruct build`, the following code
```
import texture from './texture.png';
console.log(texture);
```
will throw an error
```
🎁 info building bundles!
🎁 error package-b Error: Unexpected character '�' (Note that you need plugins to import files that are not JavaScript)
🎁 error package-b     at error (C:\Users\Arnaud A\Repos\sandbox\test-preconstruct\node_modules\rollup\dist\shared\rollup.js:7917:30)
🎁 error package-b     at Module.error (C:\Users\Arnaud A\Repos\sandbox\test-preconstruct\node_modules\rollup\dist\shared\rollup.js:9859:16)
...
```
It seems like `preconstruct` also ignores `rollup.config.js`.
How can I use additional  plugins (e.g. @rollup/plugin-image) in this case?

**Comment by mitchellhamilton** [comment]
Preconstruct doesn't support importing things like images because there isn't a standardized meaning of what importing an image should do. You also can't use Rollup plugins, Rollup is an implementation detail of Preconstruct. If you want to do something like this, you could have a Babel plugin that reads the file and inlines the bytes or does whatever behavior you're looking for.
