### ISSUE TITLE
Question: how to configure `declarationMap` properly

### ISSUE THREAD

**Issue by KATT** [preconstruct/preconstruct#410]
Hey.

Firstly - I love preconstruct - great job.

---

I'm the author of [trpc](https://github.com/trpc/trpc) & I just saw today that you've added support for declaration maps in #393.

What is the key thing I need to do to get it working - apart from setting `declarationMap: true` in my tsconfig?

I'm trying to add it here in [this PR](https://github.com/trpc/trpc/pull/877/files#diff-3ae20d611c1c7263a9c1bce0449291ebfea1c5d578b3fcdbb596353ad885db25R8) but I can't see any `d.ts.map`-files being added. Can you spot what I'm missing?

Thanks.

**Comment by mitchellhamilton** [comment]
It looks like generating declaration maps on TypeScript 4.3 and above with Preconstruct is broken because of https://github.com/microsoft/TypeScript/pull/43205/files#diff-537414476d7c7a690310c5e1e5d6a0bbbfba37c5b05126edee32fdea7e3a09d8R501 since Preconstruct uses `forceDtsEmit`. I think that ideally we wouldn't use `forceDtsEmit` since my understanding is that it's only necessary because Preconstruct's usage of the TS compiler API is incorrect in some way but I'm not quite sure how it's incorrect.

**Comment by mitchellhamilton** [comment]
If you update to [`@preconstruct/cli@2.1.2`](https://github.com/preconstruct/preconstruct/releases/tag/%40preconstruct%2Fcli%402.1.2), it should work.

**Comment by KATT** [comment]
It works! Thanks! 💃
