### ISSUE TITLE
error TS2742

### ISSUE THREAD

**Issue by matthewhausman** [preconstruct/preconstruct#500]
Getting the following error:

The inferred type of 'useAccount' cannot be named without a reference to '../../../../core/node_modules/eventemitter3'. This is likely not portable. A type annotation is necessary.

Can anyone help me understand whats going on here? thanks

**Comment by binarykitchen** [comment]
Experiencing the same here and what's even more weird, is that when checking types locally with `tsc` (typescript), this error isn't being reported.

That said, is preconstruct ignoring our local tsconfig file?

**Comment by emmatown** [comment]
> The inferred type of 'useAccount' cannot be named without a reference to '../../../../core/node_modules/eventemitter3'. This is likely not portable. A type annotation is necessary.

It means you've got some type that includes a type from `eventemitter3` though you likely don't have a direct dependency on it and TypeScript doesn't want to generate a type like `import("../../../../core/node_modules/eventemitter3")` since when published to npm, that dependency won't exist in the same place. Adding a dependency on `eventemitter3` might solve it or adding a type annotation to that export.

> Experiencing the same here and what's even more weird, is that when checking types locally with tsc (typescript), this error isn't being reported.
> 
> That said, is preconstruct ignoring our local tsconfig file?

Preconstruct reads your tsconfig file but sets `declaration` to `true`. If you set it in your tsconfig, you'll also see the error when running tsc.
